services:
  web:
    build: .
    command: sh -c "uvicorn src.main:app --reload --port=8000 --host=0.0.0.0"
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - 8000:8000

  db:
      image: postgres:16.1-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      ports:
        - 5432:5432
      env_file:
        - .env.example

volumes:
      postgres_data: